title: Ikigai
author:  Héctor García and Francesc Miralles.
email: nikithachandrasekhar99@gmail.com
description: Ikigai is a Japanese word whose meaning translates roughly to a reason for being, encompassing joy, a sense of purpose and meaning and a feeling of well-being. The word derives from iki, meaning life and kai, meaning the realisation of hopes and expectations.
